# Generated by Django 5.0.6 on 2025-07-19 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name']},
        ),
    ]
